### ISSUE TITLE
Generating restart file?

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#1558] opened 2024-06-14 13:52 UTC
Newly created models often have initial conditions that are not really suitable, which the solver handles by making small timesteps till the model is in more appropriate state.

Should we add an option (in the toml) to create a restart file at the end of the run ?

**Comment by visr** [comment] 2024-06-14 14:56
Closing as a duplicate of #1358. Since the file isn't large, I'd opt for always writing it, and not adding an option to the TOML.

**Closed by visr** 2024-06-14 14:56 UTC
Labels: physics, improvement
