### ISSUE TITLE
write function not working

### ISSUE THREAD

**Issue by harm-nomden-sweco** [Deltares/Ribasim#712] opened 2023-10-30 18:44 UTC
def _write_tables not working anymore.

code does not recognize instances as TableModel and thus does not write BasinProfile, etc to geopackage. 
fixed it locally, but probably something better

**Comment by visr** [comment] 2023-10-30 20:23
Are you saying this line is always false? I don't understand, all tests would be broken if that would happen in CI. What was you local fix? Or do you have some code to reproduce the issue?

https://github.com/Deltares/Ribasim/blob/c3c69a90d3444e11c95a9801f0d26c7015e79df8/python/ribasim/ribasim/model.py#L184

**Comment by harm-nomden-sweco** [comment] 2023-10-30 20:27
after pulling the latest version, it was alwasy false. so only Edges and Nodes were written. don't understand why
I replaced the isinstance() with 
type(input_entry) in [Basin, Output, Pump, etc.]

**Comment by visr** [comment] 2023-10-30 20:57
That seems very strange. For me this evaluates to True:

```python
import ribasim
import pandas as pd
from ribasim.input_base import TableModel

terminal = ribasim.Terminal(
    static=pd.DataFrame(
        data={
            "node_id": [4],
        }
    )
)

isinstance(terminal, TableModel)
```

**Comment by visr** [comment] 2023-10-31 10:24
Discussed with @harm-nomden-sweco, he cannot reproduce this anymore. Closing for now, please re-open if it occurs again.

**Closed as completed by visr** 2023-10-31 10:24 UTC
