### ISSUE TITLE
Allow linear interpolation for fractional flow and pump discharge

### ISSUE THREAD

**Issue by SnippenE** [Deltares/Ribasim#1019] opened 2024-01-31 21:52 UTC
**What**
User wants a more easy to implement and logical way of schematizing the control concepts for the Dutch watersystem 

**Why**
Current concepts of control are not sufficient to define control rules over a large range of discharge. This makes a model unnecessarily complex

**How**
Currently only a block function is implemented. Adding lineair interpolation for at least fractional flow and pump capacity would be sufficient to accommodate the National Usecase

**Additional context**
RWS Samenwerkingsdag jan 2024

**Comment by Huite** [comment] 2024-02-01 08:38
It's worth considering here whether linear interpolation cannot be generalized to a full piecewise linear function (like the TabulatedRatingCurves).

In principle a linear interpolation could be expressed as a linear function y = ax + b.

But when talking about pumps and the like, it seems somewhat likely that y should be bounded. E.g. a pump should not go below 0, and perhaps it should not exceed a maximum capacity either. That requires an additional four values (x_min, y_min; x_max, y_max) -- at which point it's starting to look a lot like the piecewise linear interpolation of the TabulatedRatingCurve.

**Comment by visr** [comment] 2024-02-22 09:14
Closing as a duplicate of #720. @Huite, indeed we are talking about piecewise linear interpolation here.

**Closed by visr** 2024-02-22 09:14 UTC
Labels: control, physics, Marker
