### ISSUE TITLE
Figure doesn't show properly

### ISSUE THREAD

**Issue by Fati-Mon** [Deltares/Ribasim#1663] opened 2024-07-26 13:31 UTC
**What**
Second figure does not seem right: https://deltares.github.io/Ribasim/reference/test-models.html
![image](https://github.com/user-attachments/assets/85b8fd49-c122-4a3b-a710-46cec960fdff)

It it possible to fix it?

**Comment by visr** [comment] 2024-07-29 07:59
Closing as a duplicate of #1463

**Closed by visr** 2024-07-29 07:59 UTC
Labels: documentation
