### ISSUE TITLE
Impossible to change values in tables (static, profile etc.) 

### ISSUE THREAD

**Issue by RomeijnN** [Deltares/Ribasim#1221] opened 2024-03-08 10:57 UTC
It is possible to change dataframes of nodes and edges, but values in the corresponding tables (static, profile etc.) cannot be adjusted once saved. 

Possibly, it has something to do with the different versions of Ribasim. Because, when starting a model from scratch (so without loading a model), it is possible to adjust the values in the static, profile etc. tables

Ribasim version: 2024.3.0

**Comment by visr** [comment] 2024-03-08 16:38
I cannot reproduce this myself. We did have this issue in the past https://github.com/Deltares/Ribasim/issues/841, but that has been fixed a while ago in https://github.com/Deltares/Ribasim/pull/873.

It could be that you have an older model that predates that fix, and therefore it cannot be edited. You could try adding an `fid` column yourself, but in general we don't really support models of previous Ribasim releases in a newer QGIS plugin version.

**Comment by visr** [comment] 2024-03-18 11:53
Closing for now, feel free to reopen if you see this with a recent model and QGIS version.

**Closed by visr** 2024-03-18 11:53 UTC
