### ISSUE TITLE
Investigate automated python package release

### ISSUE THREAD

**Issue by Jingru923** [Deltares/Ribasim#1583] opened 2024-06-27 07:37 UTC
During the release process, we need to manually publish Ribasim Python packages. This step seems to be automatable.

We should investigate if publishing our Python packages can also be done by the pipeline.

The outcome of this issue is a "yes" or "no" answer.

**Comment by deltamarnix** [comment] 2024-07-18 14:52
There is a Pypi publish action that could be triggered: https://github.com/marketplace/actions/pypi-publish. Is that what you are looking for?

**Comment by Jingru923** [comment] 2024-07-18 15:48
@visr our python package are released manually. The idea of this issue was to move it to TeamCity

**Comment by visr** [comment] 2024-07-18 16:08
Yeah I know. Marnix suggested a GitHub Action, but I meant that since the rest of the release pipeline is on TeamCity, a GitHub Action is not ideal.

**Comment by Huite** [comment] 2024-07-18 18:29
I think Sunny set it up for imod-python: https://deltares.github.io/imod-python/developing.html#how-to-release-a-new-version

**Comment by Jingru923** [comment] 2024-07-18 18:54
That is where I got the inspiration.

**Comment by SnippenE** [comment] 2024-09-03 14:20
close as duplicate of #669

**Closed by SnippenE** 2024-09-03 14:20 UTC
Labels: CI/CD, improvement
